//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cu_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cu_customer()
        {
            this.fpr_farmer_sells_product = new HashSet<fpr_farmer_sells_product>();
        }
    
        public int cu_id { get; set; }
        public string cu_lastname { get; set; }
        public string cu_firstname { get; set; }
        public string cu_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fpr_farmer_sells_product> fpr_farmer_sells_product { get; set; }
    }
}
