//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMSentities : DbContext
    {
        public FMSentities()
            : base("name=FMSentities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_animal> a_animal { get; set; }
        public virtual DbSet<c_corn> c_corn { get; set; }
        public virtual DbSet<cu_customer> cu_customer { get; set; }
        public virtual DbSet<f_farmer> f_farmer { get; set; }
        public virtual DbSet<fpr_farmer_sells_product> fpr_farmer_sells_product { get; set; }
        public virtual DbSet<p_property> p_property { get; set; }
        public virtual DbSet<pr_product> pr_product { get; set; }
    }
}
