//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class fpr_farmer_sells_product
    {
        public int fpr_f_farmer { get; set; }
        public int fpr_pr_product { get; set; }
        public float fpr_price { get; set; }
        public int cu_customer_cu_id { get; set; }
    
        public virtual cu_customer cu_customer { get; set; }
        public virtual f_farmer f_farmer { get; set; }
        public virtual pr_product pr_product { get; set; }
    }
}
