-- MySQL Script generated by MySQL Workbench
-- Mon 14 Mär 2016 15:09:40 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE "FMS" ;


-- -----------------------------------------------------
-- Table    f_farmer 
-- -----------------------------------------------------
CREATE TABLE f_farmer (
   f_id INT NOT NULL,
   f_firstname TEXT NOT NULL ,
   f_lastname  TEXT NOT NULL ,
   f_address TEXT NOT NULL ,
  PRIMARY KEY (f_id) );


-- -----------------------------------------------------
-- Table    pr_product 
-- -----------------------------------------------------
CREATE TABLE      pr_product  (
   pr_id  int NOT NULL  ,
   pr_type  TEXT NOT NULL  ,
   pr_class  int NULL  ,
  PRIMARY KEY ( pr_id )   )
 ;


-- -----------------------------------------------------
-- Table    a_animal 
-- -----------------------------------------------------
CREATE TABLE      a_animal  (
   a_id  int NOT NULL  ,
   a_animal  TEXT NULL  ,
   a_age  REAL NOT NULL  ,
   a_weight  REAL NOT NULL  ,
   a_classification  int NOT NULL  ,
   f_farmer_f_id  int NOT NULL  ,
   a_pr_product  int NULL  ,
  PRIMARY KEY ( a_id )   ,
  CONSTRAINT  fk_a_animal_f_farmer1 
    FOREIGN KEY ( f_farmer_f_id )
    REFERENCES    f_farmer  ( f_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT  fk_a_animal_pr_product1 
    FOREIGN KEY ( a_pr_product )
    REFERENCES    pr_product  ( pr_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 ;


-- -----------------------------------------------------
-- Table    c_corn 
-- -----------------------------------------------------
CREATE TABLE      c_corn  (
   c_id  int NOT NULL  ,
   c_type  TEXT NOT NULL  ,
   c_class  int NULL  ,
   c_dour  int NOT NULL  ,
   c_pr_product  int NULL  ,
  PRIMARY KEY ( c_id )   ,
  CONSTRAINT  fk_c_corn_pr_product1 
    FOREIGN KEY ( c_pr_product )
    REFERENCES    pr_product  ( pr_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 ;


-- -----------------------------------------------------
-- Table    p_property 
-- -----------------------------------------------------
CREATE TABLE      p_property  (
   p_id  int NOT NULL  ,
   p_name  TEXT NOT NULL  ,
   p_description  TEXT NULL  ,
   p_f_farmer  int NOT NULL  ,
   p_area  REAL NOT NULL  ,
   p_c_corn  INT NULL  ,
  PRIMARY KEY ( p_id )   ,
 
  CONSTRAINT  fk_p_property_f_farmer1 
    FOREIGN KEY ( p_f_farmer )
    REFERENCES    f_farmer  ( f_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT  fk_p_property_c_corn1 
    FOREIGN KEY ( p_c_corn )
    REFERENCES    c_corn  ( c_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 ;


-- -----------------------------------------------------
-- Table    cf_farmer_has_corn 
-- -----------------------------------------------------
CREATE TABLE      cf_farmer_has_corn  (
   cf_f_farmer  int NOT NULL  ,
   cf_c_corn  INT NOT NULL  ,
  PRIMARY KEY ( cf_f_farmer ,  cf_c_corn )   ,
  CONSTRAINT  fk_f_farmer_has_c_corn_f_farmer1 
    FOREIGN KEY ( cf_f_farmer )
    REFERENCES    f_farmer  ( f_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT  fk_f_farmer_has_c_corn_c_corn1 
    FOREIGN KEY ( cf_c_corn )
    REFERENCES    c_corn  ( c_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 ;


-- -----------------------------------------------------
-- Table    cu_customer 
-- -----------------------------------------------------
CREATE TABLE      cu_customer  (
   cu_id  int NOT NULL  ,
   cu_lastname  TEXT NOT NULL  ,
   cu_firstname  TEXT NOT NULL  ,
   cu_address  TEXT NULL  ,
  PRIMARY KEY ( cu_id )   )
 ;


-- -----------------------------------------------------
-- Table    fpr_farmer_sells_product 
-- -----------------------------------------------------
CREATE TABLE      fpr_farmer_sells_product  (
   fpr_f_farmer  int NOT NULL  ,
   fpr_pr_product  int NOT NULL  ,
   fpr_price  REAL NOT NULL  ,
   cu_customer_cu_id  int NOT NULL  ,
  PRIMARY KEY ( fpr_f_farmer ,  fpr_pr_product )   ,
  CONSTRAINT  fk_f_farmer_has_pr_product_f_farmer1 
    FOREIGN KEY ( fpr_f_farmer )
    REFERENCES    f_farmer  ( f_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT  fk_f_farmer_has_pr_product_pr_product1 
    FOREIGN KEY ( fpr_pr_product )
    REFERENCES    pr_product  ( pr_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT  fk_fpr_farmer_sells_product_cu_customer1 
    FOREIGN KEY ( cu_customer_cu_id )
    REFERENCES    cu_customer  ( cu_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 ;


