//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_property
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_description { get; set; }
        public int p_f_farmer { get; set; }
        public float p_area { get; set; }
        public Nullable<int> p_c_corn { get; set; }
    
        public virtual c_corn c_corn { get; set; }
        public virtual f_farmer f_farmer { get; set; }
    }
}
